import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

export class GoogleSheet {
  async init() {
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      key: process.env.GOOGLE_PRIVATE_KEY,
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });
    this.doc = new GoogleSpreadsheet(process.env.GOOGLE_SHEET_ID, serviceAccountAuth);

    await this.doc.loadInfo();
  }

  async writeMission(data) {
    try {
      const sheet = this.doc.sheetsByIndex[1]; // 미션 목록 시트
      await sheet.addRow(data);
    } catch (err) {
      console.error(err);
    }
  }
  async readMission() {
    try {
      const sheet = this.doc.sheetsByIndex[1]; // 미션 목록 시트
      const rows = await sheet.getRows({ offset: 1 });
      return rows.map(({ _rawData }) => _rawData);
    } catch (err) {
      console.error(err);
    }
  }
}
